# Generated by Django 5.0.1 on 2026-04-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du département"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code du département"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departements_diriges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable du département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la filière"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code de la filière"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filieres",
                        to="academic.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filière",
                "verbose_name_plural": "Filières",
                "ordering": ["departement", "nom"],
            },
        ),
        migrations.CreateModel(
            name="InscriptionNiveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_inscription",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Inscription active"
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
            },
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                            ("D1", "Doctorat 1"),
                            ("D2", "Doctorat 2"),
                            ("D3", "Doctorat 3"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(
                        help_text="Format : 2024-2025",
                        max_length=9,
                        verbose_name="Année académique",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etudiants",
                    models.ManyToManyField(
                        related_name="niveaux_inscrits",
                        through="academic.InscriptionNiveau",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiants inscrits",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux",
                        to="academic.filiere",
                        verbose_name="Filière",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["filiere", "nom"],
                "unique_together": {("filiere", "nom", "annee_academique")},
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la matière"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code de la matière"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "volume_horaire",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Volume horaire (heures)"
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveIntegerField(default=1, verbose_name="Coefficient"),
                ),
                (
                    "seuil_absences",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Nombre d'absences max avant convocation",
                        verbose_name="Seuil d'absences (zone rouge)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matieres_enseignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professeur",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matieres",
                        to="academic.niveau",
                        verbose_name="Niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["niveau", "nom"],
            },
        ),
        migrations.AddField(
            model_name="inscriptionniveau",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions",
                to="academic.niveau",
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscriptionniveau",
            unique_together={("etudiant", "niveau")},
        ),
    ]
