# Generated by Django 5.0.1 on 2026-04-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("ALERTE_ABSENCE", "Alerte absence"),
                            ("CONVOCATION", "Convocation"),
                            ("INFO", "Information"),
                            ("RAPPEL", "Rappel"),
                            ("SEANCE_ACTIVE", "Séance active"),
                        ],
                        default="INFO",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Lien de redirection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_seance", models.DateField(verbose_name="Date de la séance")),
                ("heure_debut", models.TimeField(verbose_name="Heure de début")),
                (
                    "heure_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin prévue"
                    ),
                ),
                (
                    "salle",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Salle / Lieu",
                    ),
                ),
                (
                    "code_unique",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Code de présence"
                    ),
                ),
                (
                    "code_expire_a",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Le code expire à"
                    ),
                ),
                (
                    "duree_code_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Durée du code (minutes)"
                    ),
                ),
                (
                    "latitude_prof",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude du professeur",
                    ),
                ),
                (
                    "longitude_prof",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitude du professeur",
                    ),
                ),
                (
                    "rayon_metres",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Rayon autorisé (mètres)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ACTIVE", "Active"),
                            ("CLOTUREE", "Clôturée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "heure_demarrage_reel",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de démarrage réel"
                    ),
                ),
                (
                    "heure_cloture_reel",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de clôture réelle"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances",
                        to="academic.matiere",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances_enseignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance",
                "verbose_name_plural": "Séances",
                "ordering": ["-date_seance", "-heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("ABSENT", "Absent"),
                            ("RETARD", "En retard"),
                            ("EXCUSE", "Excusé"),
                        ],
                        default="ABSENT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "heure_pointage",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure du pointage"
                    ),
                ),
                (
                    "latitude_etudiant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude de l'étudiant",
                    ),
                ),
                (
                    "longitude_etudiant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitude de l'étudiant",
                    ),
                ),
                (
                    "distance_calculee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Distance calculée (mètres)",
                    ),
                ),
                (
                    "methode_pointage",
                    models.CharField(
                        choices=[
                            ("CODE_GPS", "Code + GPS"),
                            ("MANUEL", "Manuel (professeur)"),
                            ("AUTOMATIQUE", "Automatique (système)"),
                        ],
                        default="AUTOMATIQUE",
                        max_length=20,
                        verbose_name="Méthode de pointage",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Justification (pour excuse ou modification manuelle)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presences_modifiees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="attendance.seance",
                        verbose_name="Séance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "ordering": ["-seance__date_seance", "etudiant__last_name"],
                "unique_together": {("seance", "etudiant")},
            },
        ),
    ]
